version: '3.3'
services:
  post_db:
    image: mongo:4.0.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${HOST_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${VERSION}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - front_net
      - back_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - front_net
      - back_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - back_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  mongodb-exporter:
    image: bitnami/mongodb-exporter:0.35.0
    networks:
      - back_net
    command:
      - '--mongodb.uri=mongodb://post_db'
      - '--collect-all'
  blackbox-exporter:
    image: bitnami/blackbox-exporter:0.23.0
    networks:
      - front_net
    volumes:
      - ./blackbox-exporter.yml:/opt/bitnami/blackbox-exporter/conf/config.yml

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
